# Generated by Django 4.2.3 on 2023-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodofrecovery',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelofengine',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelofmachine',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelofmainaxle',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelofsteeringaxle',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modeloftransmission',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typeoffailure',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typeofmaintenance',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
