# Generated by Django 4.2.3 on 2023-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodofrecovery',
            options={'verbose_name': 'Способ Восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='modelofengine',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателей'},
        ),
        migrations.AlterModelOptions(
            name='modelofmachine',
            options={'verbose_name': 'Модель машины', 'verbose_name_plural': 'Модели машины'},
        ),
        migrations.AlterModelOptions(
            name='modelofmainaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='modelofsteeringaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='modeloftransmission',
            options={'verbose_name': 'Модель Трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AlterModelOptions(
            name='typeoffailure',
            options={'verbose_name': 'Причина отказа', 'verbose_name_plural': 'Причины отказа'},
        ),
        migrations.AlterModelOptions(
            name='typeofmaintenance',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.RemoveField(
            model_name='methodofrecovery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelofengine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelofmachine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelofmainaxle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelofsteeringaxle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modeloftransmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='typeoffailure',
            name='name',
        ),
        migrations.RemoveField(
            model_name='typeofmaintenance',
            name='name',
        ),
        migrations.AddField(
            model_name='methodofrecovery',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modelofengine',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modelofmachine',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modelofmainaxle',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modelofsteeringaxle',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modeloftransmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeoffailure',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeofmaintenance',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelofmachine',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Модель машины'),
        ),
    ]
