# Generated by Django 4.2.3 on 2023-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CR', 'Клиент'), ('MR', 'Менеджер'), ('SC', 'Сервисная компания')], default='CR', max_length=2),
        ),
    ]
