# Generated by Django 4.2.3 on 2023-08-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
