# Generated by Django 4.2.3 on 2023-08-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CR', 'Клиент'), ('MR', 'Менеджер'), ('SC', 'Сервисная компания')], default='', max_length=2),
        ),
    ]
