# Generated by Django 4.2.3 on 2023-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Техническое Обслуживание', 'verbose_name_plural': 'Техническое Обслуживание'},
        ),
        migrations.AlterField(
            model_name='complaints',
            name='downtimeOfMachine',
            field=models.IntegerField(verbose_name='Время простоя'),
        ),
    ]
