# Generated by Django 4.2.3 on 2023-08-22 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0002_alter_order_options_alter_order_additionaloptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceServiceCompany',
            field=models.ForeignKey(default='Самостоятельно', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_servicecompany', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО'),
        ),
    ]
